using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SchedulerLib
{
    /// <summary>
    /// A task provided by a software interface. These tasks are generally generated by code to run at fixed times
    /// </summary>
    public abstract class SoftwareTask : Task
    {
    }
}
